/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "G:\\gitbook\\blog-master\\blog-master\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-eed9b3ec",
    path: "/blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eed9b3ec").then(next)
    },
  },
  {
    name: "v-08a2b95c",
    path: "/blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08a2b95c").then(next)
    },
  },
  {
    name: "v-7393de48",
    path: "/blog/edu-sys-get-data/edu-sys-get-data.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7393de48").then(next)
    },
  },
  {
    name: "v-39e8fca3",
    path: "/blog/firstBlog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39e8fca3").then(next)
    },
  },
  {
    name: "v-7456b332",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7456b332").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-531d3f44",
    path: "/blog/global-exception-handling/global-exception-handling.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-531d3f44").then(next)
    },
  },
  {
    name: "v-00a35cc2",
    path: "/blog/global-configuration-item/global-configuration-item.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00a35cc2").then(next)
    },
  },
  {
    name: "v-2b606452",
    path: "/blog/overall-curriculum-design/overall-curriculum-design.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b606452").then(next)
    },
  },
  {
    name: "v-105f0c9c",
    path: "/blog/global-request-specification/global-request-specification.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-105f0c9c").then(next)
    },
  },
  {
    name: "v-573ef59c",
    path: "/blog/user-query/user-query.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-573ef59c").then(next)
    },
  },
  {
    name: "v-9631b9ec",
    path: "/blog/user-related-services/user-related-services.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9631b9ec").then(next)
    },
  },
  {
    name: "v-9c1c06cc",
    path: "/blog/user-bind-email/user-bind-email.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c1c06cc").then(next)
    },
  },
  {
    name: "v-72ed3e52",
    path: "/blog/user-bind-phone/user-bind-phone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72ed3e52").then(next)
    },
  },
  {
    name: "v-fe7404b4",
    path: "/blog/user-update/user-update.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe7404b4").then(next)
    },
  },
  {
    name: "v-d896f28a",
    path: "/blog/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d896f28a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]