/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "中北二龙山开发文档",
  "description": "~~~~~~~~~",
  "base": "/",
  "pages": [
    {
      "title": "1 功能需求",
      "frontmatter": {},
      "regularPath": "/blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.html",
      "relativePath": "blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.md",
      "key": "v-eed9b3ec",
      "path": "/blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.html",
      "headers": [
        {
          "level": 3,
          "title": "1 功能需求",
          "slug": "_1-功能需求"
        },
        {
          "level": 3,
          "title": "2 性能需求及其他需求",
          "slug": "_2-性能需求及其他需求"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.html",
      "relativePath": "blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.md",
      "key": "v-08a2b95c",
      "path": "/blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.html"
    },
    {
      "title": "功能描述",
      "frontmatter": {},
      "regularPath": "/blog/edu-sys-get-data/edu-sys-get-data.html",
      "relativePath": "blog/edu-sys-get-data/edu-sys-get-data.md",
      "key": "v-7393de48",
      "path": "/blog/edu-sys-get-data/edu-sys-get-data.html",
      "headers": [
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求说明",
          "slug": "请求说明"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        }
      ]
    },
    {
      "title": "vuePress+github搭建博客",
      "frontmatter": {},
      "regularPath": "/blog/firstBlog.html",
      "relativePath": "blog/firstBlog.md",
      "key": "v-39e8fca3",
      "path": "/blog/firstBlog.html",
      "headers": [
        {
          "level": 3,
          "title": "一、vuePress本地项目",
          "slug": "一、vuepress本地项目"
        },
        {
          "level": 3,
          "title": "二、部署",
          "slug": "二、部署"
        },
        {
          "level": 3,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "1.jpg",
        "actionText": "来！走起！",
        "actionLink": "/blog/firstBlog.md",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present Guowenyuan"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7456b332",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/global-exception-handling/global-exception-handling.html",
      "relativePath": "blog/global-exception-handling/global-exception-handling.md",
      "key": "v-531d3f44",
      "path": "/blog/global-exception-handling/global-exception-handling.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/global-configuration-item/global-configuration-item.html",
      "relativePath": "blog/global-configuration-item/global-configuration-item.md",
      "key": "v-00a35cc2",
      "path": "/blog/global-configuration-item/global-configuration-item.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/overall-curriculum-design/overall-curriculum-design.html",
      "relativePath": "blog/overall-curriculum-design/overall-curriculum-design.md",
      "key": "v-2b606452",
      "path": "/blog/overall-curriculum-design/overall-curriculum-design.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/global-request-specification/global-request-specification.html",
      "relativePath": "blog/global-request-specification/global-request-specification.md",
      "key": "v-105f0c9c",
      "path": "/blog/global-request-specification/global-request-specification.html"
    },
    {
      "title": "2.1 用户信息查询",
      "frontmatter": {},
      "regularPath": "/blog/user-query/user-query.html",
      "relativePath": "blog/user-query/user-query.md",
      "key": "v-573ef59c",
      "path": "/blog/user-query/user-query.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1 用户信息查询",
          "slug": "_2-1-用户信息查询"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求说明",
          "slug": "请求说明"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        }
      ]
    },
    {
      "title": "1.1 登录",
      "frontmatter": {},
      "regularPath": "/blog/user-related-services/user-related-services.html",
      "relativePath": "blog/user-related-services/user-related-services.md",
      "key": "v-9631b9ec",
      "path": "/blog/user-related-services/user-related-services.html",
      "headers": [
        {
          "level": 2,
          "title": "1.1 登录",
          "slug": "_1-1-登录"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求说明",
          "slug": "请求说明"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        },
        {
          "level": 2,
          "title": "1.2 验证Token",
          "slug": "_1-2-验证token"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述-2"
        },
        {
          "level": 3,
          "title": "请求说明",
          "slug": "请求说明-2"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数-2"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果-2"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数-2"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码-2"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码-2"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/user-bind-email/user-bind-email.html",
      "relativePath": "blog/user-bind-email/user-bind-email.md",
      "key": "v-9c1c06cc",
      "path": "/blog/user-bind-email/user-bind-email.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/user-bind-phone/user-bind-phone.html",
      "relativePath": "blog/user-bind-phone/user-bind-phone.md",
      "key": "v-72ed3e52",
      "path": "/blog/user-bind-phone/user-bind-phone.html"
    },
    {
      "title": "3.1 更新用户的微信信息",
      "frontmatter": {},
      "regularPath": "/blog/user-update/user-update.html",
      "relativePath": "blog/user-update/user-update.md",
      "key": "v-fe7404b4",
      "path": "/blog/user-update/user-update.html",
      "headers": [
        {
          "level": 2,
          "title": "3.1 更新用户的微信信息",
          "slug": "_3-1-更新用户的微信信息"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求说明",
          "slug": "请求说明"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/vue.html",
      "relativePath": "blog/vue.md",
      "key": "v-d896f28a",
      "path": "/blog/vue.html",
      "headers": [
        {
          "level": 3,
          "title": "按钮",
          "slug": "按钮"
        },
        {
          "level": 3,
          "title": "导入代码段",
          "slug": "导入代码段"
        }
      ]
    }
  ],
  "themeConfig": {
    "repoLabel": "GitHub",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "博客",
        "link": "/blog/firstBlog.md"
      },
      {
        "text": "求索",
        "items": [
          {
            "text": "Segmentfault",
            "link": "https://segmentfault.com/u/mulander"
          }
        ]
      }
    ],
    "sidebar": [
      [
        "/",
        "首页"
      ],
      {
        "title": "我的博客",
        "children": [
          [
            "/blog/firstBlog.md",
            "vuePress+github搭建博客"
          ],
          [
            "/blog/vue.md",
            "md中使用vue"
          ]
        ]
      },
      {
        "title": "全局相关配置",
        "children": [
          [
            "/blog/global-exception-handling/global-exception-handling.md",
            "全局异常处理"
          ],
          [
            "/blog/global-configuration-item/global-configuration-item.md",
            "全局配置项"
          ],
          [
            "/blog/global-request-specification/global-request-specification.md",
            "全局请求规范"
          ]
        ]
      },
      {
        "title": "用户相关业务",
        "children": [
          [
            "/blog/user-related-services/user-related-services.md",
            "1. 用户登录"
          ],
          [
            "/blog/user-query/user-query.md",
            "2. 用户查询"
          ],
          [
            "/blog/user-update/user-update.md",
            "3. 用户信息更新"
          ],
          [
            "/blog/user-bind-phone/user-bind-phone.md",
            "4. 用户绑定手机"
          ],
          [
            "/blog/user-bind-email/user-bind-email.md",
            "5. 用户绑定邮箱"
          ]
        ]
      },
      {
        "title": "课表相关业务",
        "children": [
          [
            "/blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.md",
            "课表需求分析"
          ],
          [
            "/blog/overall-curriculum-design/overall-curriculum-design.md",
            "课表总体设计"
          ]
        ]
      },
      {
        "title": "成绩查询相关业务",
        "children": [
          [
            "/blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.md",
            "1.成绩查询技术设计实现"
          ],
          [
            "/blog/edu-sys-get-data/edu-sys-get-data.md",
            "2.教务系统获取数据"
          ]
        ]
      }
    ]
  }
}