/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "中北二龙山开发文档",
  "description": "~~~~~~~~~",
  "base": "/elsdoc/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "1.jpg",
        "actionText": "来！走起！",
        "actionLink": "/blog/firstBlog.md",
        "features": [
          {
            "title": "VuePress",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "Koa",
            "details": "基于 Node.js 平台的下一代 Web 开发框架。"
          },
          {
            "title": "GraphQL",
            "details": "对 API 中的数据提供了一套易于理解的完整描述，且没有任何冗余，让 API 更容易地随着时间推移而演进。"
          },
          {
            "title": "Jenkins",
            "details": "领先的开源自动化服务,用于持续集成和持续交付。"
          },
          {
            "title": "Selenium",
            "details": "优秀的Web应用程序测试工具,与Python配合进行自动化的数据获取。"
          },
          {
            "title": "PM2",
            "details": "轻量级的Node.js进程管理工具,支持性能监控，进程守护，负载均衡等功能。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present Guowenyuan"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5e9da452",
      "path": "/"
    },
    {
      "title": "1 功能需求",
      "frontmatter": {},
      "regularPath": "/blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.html",
      "relativePath": "blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.md",
      "key": "v-1a16f09a",
      "path": "/blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.html",
      "headers": [
        {
          "level": 3,
          "title": "1 功能需求",
          "slug": "_1-功能需求"
        },
        {
          "level": 3,
          "title": "2 性能需求及其他需求",
          "slug": "_2-性能需求及其他需求"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.html",
      "relativePath": "blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.md",
      "key": "v-758cebec",
      "path": "/blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.html"
    },
    {
      "title": "功能描述",
      "frontmatter": {},
      "regularPath": "/blog/edu-sys-get-data/edu-sys-get-data.html",
      "relativePath": "blog/edu-sys-get-data/edu-sys-get-data.md",
      "key": "v-c629f928",
      "path": "/blog/edu-sys-get-data/edu-sys-get-data.html",
      "headers": [
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/design-and-implementation-of-sub-lessons/design-and-implementation-of-sub-lessons.html",
      "relativePath": "blog/design-and-implementation-of-sub-lessons/design-and-implementation-of-sub-lessons.md",
      "key": "v-79510628",
      "path": "/blog/design-and-implementation-of-sub-lessons/design-and-implementation-of-sub-lessons.html"
    },
    {
      "title": "中北二龙山开发文档",
      "frontmatter": {},
      "regularPath": "/blog/firstBlog.html",
      "relativePath": "blog/firstBlog.md",
      "key": "v-4839619a",
      "path": "/blog/firstBlog.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/global-api-summary/global-api-summary.html",
      "relativePath": "blog/global-api-summary/global-api-summary.md",
      "key": "v-28b87228",
      "path": "/blog/global-api-summary/global-api-summary.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/global-configuration-item/global-configuration-item.html",
      "relativePath": "blog/global-configuration-item/global-configuration-item.md",
      "key": "v-41ae4752",
      "path": "/blog/global-configuration-item/global-configuration-item.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/global-exception-handling/global-exception-handling.html",
      "relativePath": "blog/global-exception-handling/global-exception-handling.md",
      "key": "v-177c4aee",
      "path": "/blog/global-exception-handling/global-exception-handling.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/overall-curriculum-design/overall-curriculum-design.html",
      "relativePath": "blog/overall-curriculum-design/overall-curriculum-design.md",
      "key": "v-6c6b4ee2",
      "path": "/blog/overall-curriculum-design/overall-curriculum-design.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/global-request-specification/global-request-specification.html",
      "relativePath": "blog/global-request-specification/global-request-specification.md",
      "key": "v-000e9f2c",
      "path": "/blog/global-request-specification/global-request-specification.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/proxy-server/proxy-server.html",
      "relativePath": "blog/proxy-server/proxy-server.md",
      "key": "v-75098b28",
      "path": "/blog/proxy-server/proxy-server.html"
    },
    {
      "title": "课表查询",
      "frontmatter": {},
      "regularPath": "/blog/query-curriculum-by-classid/query-curriculum-by-classid.html",
      "relativePath": "blog/query-curriculum-by-classid/query-curriculum-by-classid.md",
      "key": "v-4adf9b8c",
      "path": "/blog/query-curriculum-by-classid/query-curriculum-by-classid.html",
      "headers": [
        {
          "level": 2,
          "title": "课表查询",
          "slug": "课表查询"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        }
      ]
    },
    {
      "title": "功能描述",
      "frontmatter": {},
      "regularPath": "/blog/school-nav/school-nav.html",
      "relativePath": "blog/school-nav/school-nav.md",
      "key": "v-d1eea5a8",
      "path": "/blog/school-nav/school-nav.html",
      "headers": [
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "组合示例",
          "slug": "组合示例"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        }
      ]
    },
    {
      "title": "功能描述",
      "frontmatter": {},
      "regularPath": "/blog/schoolphonebook/schoolphonebook.html",
      "relativePath": "blog/schoolphonebook/schoolphonebook.md",
      "key": "v-e2a77554",
      "path": "/blog/schoolphonebook/schoolphonebook.html",
      "headers": [
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "组合示例",
          "slug": "组合示例"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述-2"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数-2"
        },
        {
          "level": 3,
          "title": "组合示例",
          "slug": "组合示例-2"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果-2"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述-3"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数-3"
        },
        {
          "level": 3,
          "title": "组合示例",
          "slug": "组合示例-3"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果-3"
        },
        {
          "level": 3,
          "title": "示例代码参考校园导览部分",
          "slug": "示例代码参考校园导览部分"
        }
      ]
    },
    {
      "title": "功能描述",
      "frontmatter": {},
      "regularPath": "/blog/study-room-course/study-room-course.html",
      "relativePath": "blog/study-room-course/study-room-course.md",
      "key": "v-5425f8fe",
      "path": "/blog/study-room-course/study-room-course.html",
      "headers": [
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/skimming-lessons-service-api/skimming-lessons-service-api.html",
      "relativePath": "blog/skimming-lessons-service-api/skimming-lessons-service-api.md",
      "key": "v-66fc99ec",
      "path": "/blog/skimming-lessons-service-api/skimming-lessons-service-api.html"
    },
    {
      "title": "功能描述",
      "frontmatter": {},
      "regularPath": "/blog/study-room/study-room.html",
      "relativePath": "blog/study-room/study-room.md",
      "key": "v-2a142b6c",
      "path": "/blog/study-room/study-room.html",
      "headers": [
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述-2"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数-2"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果-2"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/user-bind-email/user-bind-email.html",
      "relativePath": "blog/user-bind-email/user-bind-email.md",
      "key": "v-3da6b72a",
      "path": "/blog/user-bind-email/user-bind-email.html"
    },
    {
      "title": "2.1 用户信息查询",
      "frontmatter": {},
      "regularPath": "/blog/user-query/user-query.html",
      "relativePath": "blog/user-query/user-query.md",
      "key": "v-01e2cfa8",
      "path": "/blog/user-query/user-query.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1 用户信息查询",
          "slug": "_2-1-用户信息查询"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        }
      ]
    },
    {
      "title": "发送短信",
      "frontmatter": {},
      "regularPath": "/blog/user-bind-phone/user-bind-phone.html",
      "relativePath": "blog/user-bind-phone/user-bind-phone.md",
      "key": "v-02bc0e3c",
      "path": "/blog/user-bind-phone/user-bind-phone.html",
      "headers": [
        {
          "level": 2,
          "title": "发送短信",
          "slug": "发送短信"
        },
        {
          "level": 2,
          "title": "绑定手机号码",
          "slug": "绑定手机号码"
        }
      ]
    },
    {
      "title": "3.1 更新用户的微信信息",
      "frontmatter": {},
      "regularPath": "/blog/user-update/user-update.html",
      "relativePath": "blog/user-update/user-update.md",
      "key": "v-c83c4f94",
      "path": "/blog/user-update/user-update.html",
      "headers": [
        {
          "level": 2,
          "title": "3.1 更新用户的微信信息",
          "slug": "_3-1-更新用户的微信信息"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        }
      ]
    },
    {
      "title": "1.1 登录",
      "frontmatter": {},
      "regularPath": "/blog/user-related-services/user-related-services.html",
      "relativePath": "blog/user-related-services/user-related-services.md",
      "key": "v-508da4cc",
      "path": "/blog/user-related-services/user-related-services.html",
      "headers": [
        {
          "level": 2,
          "title": "1.1 登录",
          "slug": "_1-1-登录"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码"
        },
        {
          "level": 2,
          "title": "1.2 验证Token",
          "slug": "_1-2-验证token"
        },
        {
          "level": 3,
          "title": "功能描述",
          "slug": "功能描述-2"
        },
        {
          "level": 3,
          "title": "请求参数",
          "slug": "请求参数"
        },
        {
          "level": 3,
          "title": "返回结果",
          "slug": "返回结果-2"
        },
        {
          "level": 3,
          "title": "返回参数",
          "slug": "返回参数-2"
        },
        {
          "level": 3,
          "title": "错误状态码",
          "slug": "错误状态码-2"
        },
        {
          "level": 3,
          "title": "示例代码",
          "slug": "示例代码-2"
        }
      ]
    }
  ],
  "themeConfig": {
    "repoLabel": "GitHub",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "博客",
        "link": "/blog/firstBlog.md"
      },
      {
        "text": "求索",
        "items": [
          {
            "text": "Segmentfault",
            "link": "https://guowy.club"
          }
        ]
      }
    ],
    "sidebar": [
      [
        "/",
        "首页"
      ],
      {
        "title": "全局相关配置",
        "children": [
          [
            "/blog/global-api-summary/global-api-summary.md",
            "全局接口总览"
          ],
          [
            "/blog/global-exception-handling/global-exception-handling.md",
            "全局异常处理"
          ],
          [
            "/blog/global-configuration-item/global-configuration-item.md",
            "全局配置项"
          ],
          [
            "/blog/global-request-specification/global-request-specification.md",
            "全局请求规范"
          ],
          [
            "/blog/proxy-server/proxy-server.md",
            "代理服务器"
          ]
        ]
      },
      {
        "title": "用户相关业务",
        "children": [
          [
            "/blog/user-related-services/user-related-services.md",
            "1. 用户登录"
          ],
          [
            "/blog/user-query/user-query.md",
            "2. 用户查询"
          ],
          [
            "/blog/user-update/user-update.md",
            "3. 用户信息更新"
          ],
          [
            "/blog/user-bind-phone/user-bind-phone.md",
            "4. 用户绑定手机"
          ],
          [
            "/blog/user-bind-email/user-bind-email.md",
            "5. 用户绑定邮箱"
          ]
        ]
      },
      {
        "title": "课表相关业务",
        "children": [
          [
            "/blog/demand-analysis-of-curriculum/demand-analysis-of-curriculum.md",
            "课表需求分析"
          ],
          [
            "/blog/overall-curriculum-design/overall-curriculum-design.md",
            "课表总体设计"
          ],
          [
            "/blog/query-curriculum-by-classid/query-curriculum-by-classid.md",
            "根据班级查询课表"
          ]
        ]
      },
      {
        "title": "成绩查询相关业务",
        "children": [
          [
            "/blog/design-and-implementation-of-grade-query/design-and-implementation-of-grade-query.md",
            "1.成绩查询技术设计实现"
          ],
          [
            "/blog/edu-sys-get-data/edu-sys-get-data.md",
            "2.教务系统获取数据"
          ]
        ]
      },
      {
        "title": "校园导览相关",
        "children": [
          [
            "/blog/school-nav/school-nav.md",
            "读取校园导览的数据"
          ]
        ]
      },
      {
        "title": "校园电话本相关",
        "children": [
          [
            "/blog/schoolphonebook/schoolphonebook.md",
            "读取校园电话本的数据"
          ]
        ]
      },
      {
        "title": "蹭课相关业务",
        "children": [
          [
            "/blog/design-and-implementation-of-sub-lessons/design-and-implementation-of-sub-lessons.md",
            "1.蹭课设计实现"
          ],
          [
            "/blog/skimming-lessons-service-api/skimming-lessons-service-api.md",
            "2.蹭课业务接口"
          ]
        ]
      },
      {
        "title": "自习室查询业务",
        "children": [
          [
            "/blog/study-room/study-room.md",
            "1.自习室查询"
          ],
          [
            "/blog/study-room-course/study-room-course.md",
            "2.自习室课表查询"
          ]
        ]
      }
    ]
  }
}